config:
  countdown: "true" #
  time: "3" # time to teleports into lobby
  command_delay: "true"
  delay_time: "3" # cooldown

# random / lessplayers
  tp_mode: "lessplayers"
  lobbys:
  commands:
    lobby:
      command: "lobby"
      permission: "lobby.use"
      aliases:
        - "hub"
      denied_servers:
